server:
  port: 8082

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/Shopping?useSSL=false
    username: root
    password: Optimist@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: CATEGORY_SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
